baseURL: https://hellomyzn.github.io/blog/public/
languageCode: en-us
title: Blog
paginate: 5
theme: PaperMod

# https://open-groove.net/other-tools/hugo-github-pages-blog/
params:
    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
